titl: EDM_Portfolio
logo: Image/profile.jpg
Description: City College of Angeles Student studying BSIS 
show_downloads: true
google_analytics: 
remote_theme: BDHU/minimalist@v0.1.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
